runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  max_instances: 1

skip_files:
- ^(.*/)?(\.git/.*)$

handlers:
- url: /ads\.txt
  static_files: ads.txt
  upload: ads\.txt

- url: /favicon\.ico
  static_files: static/resources/favicon.ico
  upload: static/resources/favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /google392c8e9117089539\.html
  static_files: static/google392c8e9117089539.html
  upload: static/google392c8e9117089539\.html

- url: /static/resources/(.*\.svg)
  static_files: static/resources/\1
  upload: static/resources/(.*\.svg)
  mime_type: image/svg+xml
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /static/resources/(.*\.gif)
  static_files: static/resources/\1
  upload: static/resources/(.*\.gif)
  mime_type: image/gif
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /static/resources/(.*\.png)
  static_files: static/resources/\1
  upload: static/resources/(.*\.png)
  mime_type: image/png
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /static/js/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)
  mime_type: application/javascript
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /static/css/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)
  mime_type: text/css
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /static
  static_dir: static

- url: /p/(.*\.svg)
  static_files: static/editor/\1
  upload: static/editor/(.*\.svg)
  mime_type: image/svg+xml
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /p/(.*\.eot)
  static_files: static/editor/\1
  upload: static/editor/(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /p/(.*\.ttf)
  static_files: static/editor/\1
  upload: static/editor/(.*\.ttf)
  mime_type: application/octet-stream
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /p/(.*\.woff)
  static_files: static/editor/\1
  upload: static/editor/(.*\.woff)
  mime_type: application/x-woff
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /p/(.*\.png)
  static_files: static/editor/\1
  upload: static/editor/(.*\.png)
  mime_type: image/png
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /p/(.*\.(?:css|js))
  static_files: static/editor/\1
  upload: static/editor/(.*\.(css|js))
  http_headers:
    Cache-Control: public, max-age=31536000

- url: /.*
  script: main.app
  secure: always
  redirect_http_response_code: 301

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: "2.6"

- name: lxml
  version: "latest"